
// Solo el encargado puede agregar usuarios
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author aquin
 */
public class Agregar_Usuarios extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Agregar_Usuarios.class.getName());

    /**
     * Creates new form Agregar_Usuarios
     */
    // Constructor
    public Agregar_Usuarios() {

        setTitle("Agregar Usuarios");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/icon.jpg")).getImage());
        initComponents();
        this.pack(); // ajusta tamaño correcto
        this.setLocationRelativeTo(null); // centra 
        validarPermisos();
        actualizarComboRoles();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ver_usu = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        Contra = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        Contraseña = new javax.swing.JLabel();
        Usuario1 = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        Contra1 = new javax.swing.JPasswordField();
        Usu1 = new javax.swing.JTextField();
        tit = new javax.swing.JLabel();
        roles = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(102, 153, 255));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("VER USUARIOS");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, -1, -1));

        ver_usu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Contraseña", "Rol", "Estado"
            }
        ));
        jScrollPane1.setViewportView(ver_usu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 370, 310));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Cerrar Sesión --->");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 620, -1, -1));

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        Logout.addActionListener(this::LogoutActionPerformed);
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 590, 80, 90));

        Contra.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        Contra.setForeground(new java.awt.Color(204, 204, 204));
        Contra.setText("jPasswordField1");
        getContentPane().add(Contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 190, 40));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("AGREGAR USUARIO");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 210, -1));

        Contraseña.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        Contraseña.setText("Contraseña");
        getContentPane().add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        Usuario1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Usuario1.setForeground(new java.awt.Color(255, 255, 255));
        Usuario1.setText("Usuario");
        getContentPane().add(Usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        Usuario.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setText("Validar contraseña");
        getContentPane().add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        Contra1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Contra1.setForeground(new java.awt.Color(204, 204, 204));
        Contra1.setText("jPasswordField1");
        getContentPane().add(Contra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 190, 40));
        getContentPane().add(Usu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 190, 40));

        tit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mantenimiento/agregar/agregar2.png"))); // NOI18N
        getContentPane().add(tit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        roles.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        roles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ROL", "Encargado", "Supervisor", "Empleado" }));
        roles.addActionListener(this::rolesActionPerformed);
        getContentPane().add(roles, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 204));
        jLabel6.setText("<--- Volver al Menú Principal");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 620, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menup.png"))); // NOI18N
        jButton3.setText("men_prin");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 70, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mantenimiento/agregar/agregar1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Logout
    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed

        Usuarios.cerrarSesion(this);

    }//GEN-LAST:event_LogoutActionPerformed

    private void rolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolesActionPerformed

    }//GEN-LAST:event_rolesActionPerformed

    // Botón agregar
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String usuario = Usu1.getText();
        String pass = Contra1.getText();
        String pass2 = Contra.getText();
        String rol = roles.getSelectedItem().toString();

        // -------------------------- VALIDACIONES -------------------------
        if (usuario.isEmpty() || pass.isEmpty() || pass2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!pass.equals(pass2)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String error = Usuarios.validarPassword(pass);
        if (error != null) {
            JOptionPane.showMessageDialog(this, error, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Encargado
        if (rol.equals("Encargado")) {

            int confirmar = JOptionPane.showConfirmDialog(
                    this,
                    "Solo puede existir 1 encargado.\n¿Desea reemplazar al encargado actual?",
                    "Confirmar",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirmar != JOptionPane.YES_OPTION) {
                return;
            }

            // Buscar encargado activo actual
            int indexEnc = -1;
            for (int i = 0; i < Usuarios.usuarios.length; i++) {
                if (Usuarios.usuarios[i][3].equals("Encargado")
                        && Usuarios.usuarios[i][4].equals("ACTIVO")) {
                    indexEnc = i;
                    break;
                }
            }

            // Si existe encargado activo → pedir credenciales
            if (indexEnc != -1) {
                String userEnc = JOptionPane.showInputDialog("Usuario encargado actual:");
                String passEnc = JOptionPane.showInputDialog("Contraseña del encargado actual:");

                if (!Usuarios.usuarios[indexEnc][1].equals(userEnc)
                        || !Usuarios.usuarios[indexEnc][2].equals(passEnc)) {

                    JOptionPane.showMessageDialog(this,
                            "Credenciales del encargado incorrectas\nNo se puede asignar nuevo encargado",
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                    return;
                }

                // inactivar al usuario viejo
                Usuarios.usuarios[indexEnc][4] = "INACTIVO";

                // Si es el mismo que está logueado, debe cerrar sesión
                if (Usuarios.Sesion.usuarioActual.equals(userEnc)) {

                    JOptionPane.showMessageDialog(this, "Encargado reemplazado",
                            "Operación Exitosa", JOptionPane.INFORMATION_MESSAGE);
                    JOptionPane.showMessageDialog(this,
                            "Su usuario ha sido inactivado\nSerá redirigido al inicio de sesión",
                            "Sesión finalizada", JOptionPane.WARNING_MESSAGE);
                    this.dispose();
                    new Login().setVisible(true);
                }
            }

            // Crear nuevo encargado (No se borra el viejo)
            String[][] nuevoEnc = new String[Usuarios.usuarios.length + 1][5];

            for (int i = 0; i < Usuarios.usuarios.length; i++) {
                nuevoEnc[i] = Usuarios.usuarios[i];
            }

            nuevoEnc[nuevoEnc.length - 1] = new String[]{
                generarID(),
                usuario,
                pass,
                "Encargado",
                "ACTIVO"
            };

            Usuarios.usuarios = nuevoEnc;

            Usuarios.limpiarCampos(Usu1);
            Usuarios.limpiarPassword(Contra1, Contra);
            roles.setSelectedIndex(0);

            return;
        }

        // Supervisores
        if (rol.equals("Supervisor") && contarSupervisor() >= 3) {

            JOptionPane.showMessageDialog(this,
                    "Se alcanzó el límite de 3 supervisores\n"
                    + "Por favor modifique un usuario para agregar un nuevo supervisor",
                    "Límite alcanzado",
                    JOptionPane.WARNING_MESSAGE);

            Modif_Usuarios mod = new Modif_Usuarios();
            mod.setVisible(true);
            this.dispose();
            return;
        }

        // Empleados
        String[][] nuevo = new String[Usuarios.usuarios.length + 1][5];

        for (int i = 0; i < Usuarios.usuarios.length; i++) {
            nuevo[i] = Usuarios.usuarios[i];
        }

        nuevo[nuevo.length - 1] = new String[]{
            generarID(),
            usuario,
            pass,
            rol,
            "ACTIVO"
        };

        Usuarios.usuarios = nuevo;

        JOptionPane.showMessageDialog(this,
                "Usuario agregado correctamente",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);

        Usuarios.limpiarCampos(Usu1);
        Usuarios.limpiarPassword(Contra1, Contra);
        roles.setSelectedIndex(0);


    }//GEN-LAST:event_jButton1ActionPerformed

    // Mostrar usuarios registrados
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        JOptionPane.showMessageDialog(this, "Mostrando usuarios registrados", "Información", JOptionPane.INFORMATION_MESSAGE);
        Usuarios.cargarTabla(ver_usu);

    }//GEN-LAST:event_jButton2ActionPerformed

    //Regresar al menú principal
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Usuarios.regresarMenu(this);

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Contar supervisores
    private int contarSupervisor() {

        int contador = 0;

        for (int i = 0; i < Usuarios.usuarios.length; i++) {

            if (Usuarios.usuarios[i][3].equalsIgnoreCase("Supervisor") && Usuarios.usuarios[i][4].equalsIgnoreCase("ACTIVO")) {
                contador++;
            }
        }

        return contador;
    }

    // Ocultar opciones del comboBox
    private void actualizarComboRoles() {

        roles.removeAllItems();

        // Si ya hay 3 supervisores activos se bloquea
        if (contarSupervisor() >= 3) {
            roles.addItem("Encargado");
            roles.addItem("Empleado");
            roles.setSelectedItem("Empleado");
        } else {
            // Todas las opciones disponibles
            roles.addItem("Encargado");
            roles.addItem("Supervisor");
            roles.addItem("Empleado");
        }

        roles.setEnabled(true);

    }

    // Método para generar ID
    private String generarID() {

        return Usuarios.generarID();

    }

    // Validar permisos de acceso
    private void validarPermisos() {

        String rol = Usuarios.Sesion.rolActual;

        if (!rol.equals("Encargado")) {
            JOptionPane.showMessageDialog(this, "No tienes permiso de agregar nuevos usuarios.\n" + "Solo el encargado general puede agregar nuevos usuarios",
                    "Error", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Agregar_Usuarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Contra;
    private javax.swing.JPasswordField Contra1;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JButton Logout;
    private javax.swing.JTextField Usu1;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel Usuario1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> roles;
    private javax.swing.JLabel tit;
    private javax.swing.JTable ver_usu;
    // End of variables declaration//GEN-END:variables

} // FIN

