
// Solo el encargado puede inactivar usuarios

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author aquin
 */
public class Inactivar_Usuarios extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inactivar_Usuarios.class.getName());

    /**
     * Creates new form Inactivar_Usuarios
     */
    //Constructor
    public Inactivar_Usuarios() {

        setTitle("Inactivar Usuarios");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/icon.jpg")).getImage());
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        inactivar.setVisible(false);

        // Detectar selección en tabla
        ver_usu.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                if (ver_usu.getSelectedRow() >= 0) {
                    inactivar.setVisible(true);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ver_usu = new javax.swing.JTable();
        ver = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        tit = new javax.swing.JLabel();
        inactivar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ver_usu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Contraseña", "Rol", "Estado"
            }
        ));
        jScrollPane1.setViewportView(ver_usu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 570, 230));

        ver.setBackground(new java.awt.Color(51, 0, 204));
        ver.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        ver.setForeground(new java.awt.Color(255, 255, 255));
        ver.setText("VER USUARIOS");
        ver.addActionListener(this::verActionPerformed);
        getContentPane().add(ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 210, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Cerrar Sesión --->");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 640, -1, -1));

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        Logout.addActionListener(this::LogoutActionPerformed);
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 590, 80, 90));

        tit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mantenimiento/inactivar/inac2.png"))); // NOI18N
        getContentPane().add(tit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -10, -1, -1));

        inactivar.setBackground(new java.awt.Color(51, 0, 204));
        inactivar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        inactivar.setForeground(new java.awt.Color(255, 255, 255));
        inactivar.setText("INACTIVAR USUARIO");
        inactivar.addActionListener(this::inactivarActionPerformed);
        getContentPane().add(inactivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 210, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 204));
        jLabel6.setText("<--- Volver al Menú Principal");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 640, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menup.png"))); // NOI18N
        jButton3.setText("men_prin");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 70, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mantenimiento/inactivar/inac1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Ver y seleccionar usuarios
    private void verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verActionPerformed

        Usuarios.cargarTabla(ver_usu);
        JOptionPane.showMessageDialog(this, "Seleccione el usuario a inactivar", "Información", JOptionPane.INFORMATION_MESSAGE);

        inactivar.setVisible(false);

    }//GEN-LAST:event_verActionPerformed

    // Logout
    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed

        Usuarios.cerrarSesion(this);

    }//GEN-LAST:event_LogoutActionPerformed

    // Botón para inactivar usuarios
    private void inactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inactivarActionPerformed

        int fila = ver_usu.getSelectedRow();

        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario", "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String id = ver_usu.getValueAt(fila, 0).toString();
        String rol = ver_usu.getValueAt(fila, 3).toString();
        String estado = ver_usu.getValueAt(fila, 4).toString();

        // --------------------------- LINEAMIENTOS PARA INACTIVAR UN USUARIO -------------------------
        // No se puede inactivar al encargado
        if (rol.equalsIgnoreCase("Encargado")) {
            JOptionPane.showMessageDialog(this, "No puedes inactivar al encargado",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // El usuario ya está inactivo
        if (estado.equalsIgnoreCase("INACTIVO")) {
            JOptionPane.showMessageDialog(this, "El usuario ya está inactivo",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea inactivar este usuario?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            inactivarUsuario(id);
            JOptionPane.showMessageDialog(this, "Usuario inactivo", "Operación exitosa", JOptionPane.INFORMATION_MESSAGE);
            Usuarios.cargarTabla(ver_usu);
            inactivar.setVisible(false);
        }

    }//GEN-LAST:event_inactivarActionPerformed

    // Regresar al menú principal
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Usuarios.regresarMenu(this);

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Método para inactivar
    private void inactivarUsuario(String id) {

        for (int i = 0; i < Usuarios.usuarios.length; i++) {

            if (Usuarios.usuarios[i][0].equals(id)) {
                Usuarios.usuarios[i][4] = "INACTIVO";
                return;
            }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Inactivar_Usuarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton inactivar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tit;
    private javax.swing.JButton ver;
    private javax.swing.JTable ver_usu;
    // End of variables declaration//GEN-END:variables

} // FIN
