
//Solo el encargado y los supervisores pueden acceder a este menú

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author aquin
 */
public class Manten_Usuario extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Manten_Usuario.class.getName());

    /**
     * Creates new form Manten_Usuario
     */
    private String rolUsuario;

    //Constructor
    public Manten_Usuario(String rolUsuario) {

        setTitle("Mantenimiento de Usuarios");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/icon.jpg")).getImage());
        this.rolUsuario = rolUsuario;
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        validarPermisos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        inactivar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        agregar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mantenimiento/mant2.png"))); // NOI18N
        getContentPane().add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mantenimiento/mant3.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 480, 140));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Cerrar Sesión --->");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, -1, -1));

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        Logout.addActionListener(this::LogoutActionPerformed);
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 80, 90));

        inactivar.setBackground(new java.awt.Color(153, 153, 153));
        inactivar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        inactivar.setForeground(new java.awt.Color(255, 255, 255));
        inactivar.setText("INACTIVAR USUARIOS");
        inactivar.addActionListener(this::inactivarActionPerformed);
        getContentPane().add(inactivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 230, 60));

        modificar.setBackground(new java.awt.Color(204, 204, 204));
        modificar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        modificar.setForeground(new java.awt.Color(255, 255, 255));
        modificar.setText("MODIFICAR USUARIOS");
        modificar.addActionListener(this::modificarActionPerformed);
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 230, 60));

        agregar.setBackground(new java.awt.Color(153, 153, 153));
        agregar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setText("AGREGAR USUARIOS");
        agregar.addActionListener(this::agregarActionPerformed);
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 230, 60));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 204));
        jLabel6.setText("<--- Volver al Menú Principal");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menup.png"))); // NOI18N
        jButton5.setText("men_prin");
        jButton5.addActionListener(this::jButton5ActionPerformed);
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 70, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mantenimiento/mant1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Logout
    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed

        Usuarios.cerrarSesion(this);

    }//GEN-LAST:event_LogoutActionPerformed

    // Agregar Usuarios
    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed

        if (Usuarios.Sesion.rolActual.equalsIgnoreCase("Supervisor")) {
            JOptionPane.showMessageDialog(this, "Acceso denegado\nLos supervisores no pueden agregar usuarios",
                    "Permiso denegado", JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        Agregar_Usuarios agre_usu = new Agregar_Usuarios();
        agre_usu.setLocationRelativeTo(null);
        agre_usu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_agregarActionPerformed

    // Modificar Usuarios
    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed

        Modif_Usuarios mod_usu = new Modif_Usuarios();
        mod_usu.setLocationRelativeTo(null);
        mod_usu.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_modificarActionPerformed

    // Inactivar Usuarios
    private void inactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inactivarActionPerformed

        if (Usuarios.Sesion.rolActual.equalsIgnoreCase("Supervisor")) {
            JOptionPane.showMessageDialog(this, "Acceso denegado\nLos supervisores no pueden inactivar usuarios",
                    "Permiso denegado", JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        Inactivar_Usuarios inac_usu = new Inactivar_Usuarios();
        inac_usu.setLocationRelativeTo(null);
        inac_usu.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_inactivarActionPerformed

    // Regresar al menú principal
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        Usuarios.regresarMenu(this);

    }//GEN-LAST:event_jButton5ActionPerformed

    // Validar permisos para ingresar a agregar, modificar e inactivar usuarios según el rol del usuario en sesión
    private void validarPermisos() {

        if (rolUsuario.equalsIgnoreCase("Encargado")) {
            // Encargado tiene acceso total
            agregar.setEnabled(true);
            modificar.setEnabled(true);
            inactivar.setEnabled(true);

        } else if (rolUsuario.equalsIgnoreCase("Supervisor")) {
            // Supervisor puede entrar, pero solo modificar
            agregar.setEnabled(true);
            inactivar.setEnabled(true);
            modificar.setEnabled(true);

        } else {
            // Empleados NO pueden entrar aquí
            JOptionPane.showMessageDialog(this, "No tiene permiso para acceder a este menú",
                    "Acceso denegado", JOptionPane.WARNING_MESSAGE);
            new Login().setVisible(true);
            this.dispose();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Manten_Usuario("Encargado").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton agregar;
    private javax.swing.JLabel img;
    private javax.swing.JButton inactivar;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton modificar;
    // End of variables declaration//GEN-END:variables

} // FIN
