
// Solo el encargado y los supervisores pueden modificar usuarios

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author aquin
 */
public class Modif_Usuarios extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Modif_Usuarios.class.getName());

    /**
     * Creates new form Modif_Usuarios
     */
    private String rolUsuario;

    // Constructor
    public Modif_Usuarios() {

        setTitle("Modificar Usuarios");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/icon.jpg")).getImage());
        this.rolUsuario = rolUsuario;
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        modi.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ver_usu = new javax.swing.JTable();
        modi = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        manten = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mantenimiento/modificar/modi2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 204, 255));
        jLabel4.setText("Cerrar Sesión --->");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 570, -1, -1));

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        Logout.addActionListener(this::LogoutActionPerformed);
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 80, 90));

        ver_usu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Contraseña", "Rol", "Estado"
            }
        ));
        jScrollPane1.setViewportView(ver_usu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 570, 310));

        modi.setBackground(new java.awt.Color(51, 0, 153));
        modi.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        modi.setForeground(new java.awt.Color(255, 255, 255));
        modi.setText("MODIFICAR USUARIO");
        modi.addActionListener(this::modiActionPerformed);
        getContentPane().add(modi, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 210, -1));

        jButton2.setBackground(new java.awt.Color(51, 0, 153));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("VER USUARIOS");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 180, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 204));
        jLabel6.setText("<--- Volver a Mantenimiento de Usuario");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, -1, -1));

        manten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menup.png"))); // NOI18N
        manten.setText("men_prin");
        manten.addActionListener(this::mantenActionPerformed);
        getContentPane().add(manten, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 70, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mantenimiento/modificar/modi3.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Logout
    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed

        Usuarios.cerrarSesion(this);

    }//GEN-LAST:event_LogoutActionPerformed

    // Ver y seleccionar usuarios
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Usuarios.cargarTabla(ver_usu);
        JOptionPane.showMessageDialog(this, "Seleccione el usuario a modificar", "Información", JOptionPane.INFORMATION_MESSAGE);
        modi.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    // Botón Modificar Usuarios
    private void modiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modiActionPerformed

        int fila = ver_usu.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario", "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String id = ver_usu.getValueAt(fila, 0).toString();
        String rolActual = ver_usu.getValueAt(fila, 3).toString();

        // -------------------------- PEDIR NUEVOS DATOS -------------------------
        // Pedir nuevo usuario 
        String nuevoUsuario = JOptionPane.showInputDialog(this, "Nuevo usuario:");
        if (nuevoUsuario == null || nuevoUsuario.trim().isEmpty()) {
            return;
        }

        // Pedir y validad nueva contraseña
        String nuevaPass = JOptionPane.showInputDialog(this, "Nueva contraseña:");
        if (nuevaPass == null || nuevaPass.trim().isEmpty()) {
            return;
        }
        String validarPass = JOptionPane.showInputDialog(this, "Validar contraseña:");
        if (!nuevaPass.equals(validarPass)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String error = Usuarios.validarPassword(nuevaPass);
        if (error != null) {
            JOptionPane.showMessageDialog(this, error, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Pedir nuevo rol
        String nuevoRol;
        String[] opciones = {"Encargado", "Supervisor", "Empleado"};
        boolean rolValido = false;
        while (!rolValido) {

            nuevoRol = (String) JOptionPane.showInputDialog(this, "Seleccione nuevo rol:", "Modificar Rol",
                    JOptionPane.QUESTION_MESSAGE, null, opciones, rolActual);

            // Si cancela
            if (nuevoRol == null) {
                return;
            }

            // Validar rol de supervisor
            if (nuevoRol.equals("Supervisor") && contar_supervisor() >= 3) {
                JOptionPane.showMessageDialog(this, "Límite de Supervisores alcanzado\nSeleccione otro rol",
                        "Límite alcanzado", JOptionPane.WARNING_MESSAGE);
                continue; // Vuelve a pedir rol
            }

            // Validar rol para cambiar de encargado
            if (nuevoRol.equals("Encargado")) {
                int confirmar = JOptionPane.showConfirmDialog(
                        this,
                        "¿Desea asignar un nuevo encargado?\nSolo puede existir 1 encargado activo.",
                        "Confirmar cambio",
                        JOptionPane.YES_NO_OPTION
                );
                if (confirmar != JOptionPane.YES_OPTION) {
                    return;
                }
                int indexEncargado = -1;
                String userEnc = "";
                String passEnc = "";

                for (int i = 0; i < Usuarios.usuarios.length; i++) {
                    if (Usuarios.usuarios[i][3].equals("Encargado")
                            && Usuarios.usuarios[i][4].equals("ACTIVO")) {
                        indexEncargado = i;
                        userEnc = Usuarios.usuarios[i][1];
                        passEnc = Usuarios.usuarios[i][2];
                        break;
                    }
                }

                String userInput = JOptionPane.showInputDialog("Usuario encargado actual:");
                String passInput = JOptionPane.showInputDialog("Contraseña:");

                if (userInput == null || passInput == null || !userInput.equals(userEnc) || !passInput.equals(passEnc)) {

                    JOptionPane.showMessageDialog(this, "Credenciales incorrectas", "Denegado", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                Usuarios.usuarios[indexEncargado][4] = "INACTIVO"; // Se inactiva el encargado anterior, ya que solo se permite tener 1 encargado cativo registrado

                for (int i = 0; i < Usuarios.usuarios.length; i++) {
                    if (Usuarios.usuarios[i][0].equals(id)) {
                        Usuarios.usuarios[i][1] = nuevoUsuario;
                        Usuarios.usuarios[i][2] = nuevaPass;
                        Usuarios.usuarios[i][3] = "Encargado";
                        Usuarios.usuarios[i][4] = "ACTIVO";
                        if (Usuarios.Sesion.usuarioActual.equals(userEnc)) {
                            JOptionPane.showMessageDialog(this, "Encargado modificado", "Operación Exitosa", JOptionPane.INFORMATION_MESSAGE);
                            JOptionPane.showMessageDialog(this,"Su usuario ha sido inactivado\n"
                                    + "Será redirigido al inicio de sesión", "Sesión finalizada", JOptionPane.WARNING_MESSAGE);
                            this.dispose();
                            new Login().setVisible(true);
                            return;
                        }
                    }
                }

                JOptionPane.showMessageDialog(this, "Encargado actualizado", "Operación Exitosa", JOptionPane.INFORMATION_MESSAGE);
                rolValido = true;

            } else {
                //Modificar los datos
                for (int i = 0; i < Usuarios.usuarios.length; i++) {

                    if (Usuarios.usuarios[i][0].equals(id)) {
                        Usuarios.usuarios[i][1] = nuevoUsuario;
                        Usuarios.usuarios[i][2] = nuevaPass;
                        Usuarios.usuarios[i][3] = nuevoRol;
                        break;
                    }
                }

                JOptionPane.showMessageDialog(this, "Usuario modificado", "Operación Exitosa", JOptionPane.INFORMATION_MESSAGE);
                rolValido = true;
            }
        }
        // Actualizar tabla
        Usuarios.cargarTabla(ver_usu);
        modi.setVisible(false);
    }//GEN-LAST:event_modiActionPerformed

    // Regresar al menú principal
    private void mantenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mantenActionPerformed

        Usuarios.regresarMenu(this);

    }//GEN-LAST:event_mantenActionPerformed

    /**
     * @param args the command line arguments
     */
    // Método contar supervisores
    private int contar_supervisor() {

        int contador = 0;

        for (int i = 0; i < Usuarios.usuarios.length; i++) {
            if (Usuarios.usuarios[i][3].equalsIgnoreCase("Supervisor") && Usuarios.usuarios[i][4].equalsIgnoreCase("ACTIVO")) {
                contador++; // Solo se permiten 3 supervisores activos registrados
            }
        }
        return contador;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Modif_Usuarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manten;
    private javax.swing.JButton modi;
    private javax.swing.JTable ver_usu;
    // End of variables declaration//GEN-END:variables

} // FIN
